# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8072d633029a2aa98a5efe3f7611a7e369ed2ee0b864758468c09dc453a661a599182b95a0c4a140426b9688be19e6a0452d6c141049218679010f76631f13a7

test:
  secret_key_base: b5037d3940e02974e94b20768bd9a8b31e00376e38b3cb1a4d4bc863c9696b23dacb913002010f044deed36c33881581fecbefa2c1e5500ef8d77882ca679190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
